### ISSUE TITLE
[Proposal] Add `pre-commit`

### ISSUE THREAD

**Issue by SauravMaheshkar** [giotto-ai/giotto-deep#101]
Hey maintainers 👋🏽 ☕ , I noticed that most of (if not all) the steps of the **[Python Coding Style](https://giotto-ai.github.io/gtda-docs/latest/contributing/#python-coding-style)** can be automated via [pre-commit](https://pre-commit.com/) such as `flake8` and `pytest` or even the ones in the GH actions such as `mypy`. Having [pre-commit](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions. Maybe this could even help with #67 if we add `black` as a hook

**Additional context**
Although this would add `pre-commit` as a dependency for the project.

**Comment by raphaelreinauer** [comment]
Thanks for the suggestion, @SauravMaheshkar ! Great idea. I have added pre-commit as a dependency in the project and a pre-commit config file. I have also added black as a hook. Let me know if there's anything else you think we should add.

**Comment by SauravMaheshkar** [comment]
#102 looks good 👍🏽
