### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by raphaelreinauer** [giotto-ai/giotto-deep#105]
**Is your feature request related to a problem? Please describe.**
The repository contains a lot of branches that are outdated. My suggestion is to remove them, to get an overview of all useful branch
For pull-requests use forks, because they can be easily removed or back merged to another branch
**Describe the solution you'd like**
Just delete longer outdated branches
**Additional context**
The aim is to remove the outdated branch
Why should it be removed?
– Because it’s outdated
– Because the codebase can confuse people who contribute code
– Because removing it will make maintaining the codebase easier

**Comment by matteocao** [comment]
@nberkouk there are two branches : one with the smale quiver and the other with the work of Dan. Is that work saved somewhere? Can I remove the branches?

**Comment by matteocao** [comment]
the branches have been cleaned up!
