### ISSUE TITLE
basic_tutorial_image.ipynb broken: keyword grid_b is not recognized

### ISSUE THREAD

**Issue by WurmD** [giotto-ai/giotto-deep#129]
When installing as recomended `python -m pip install -U giotto-deep` it installs the latest versions of torch and other packages, it does not install `torch==1.12.1`

And this causes basic_tutorial_image.ipynb to be broken

https://github.com/giotto-ai/giotto-deep/blob/8d318c4fabe93b2747b1d496e0bf745cc8aec82d/examples/basic_tutorial_image.ipynb#L280

yields:

```
ValueError: keyword grid_b is not recognized; valid keywords are ['size', ... 'grid_ms']
```

If one installs the versions in requirements.txt `pip install -r requirements.txt` 

https://github.com/giotto-ai/giotto-deep/blob/8d318c4fabe93b2747b1d496e0bf745cc8aec82d/examples/basic_tutorial_image.ipynb#L263

yields

```
ValueError: No builder registered for key GuidedGradCam
```

**Comment by RaphaelLilt** [comment]
@matteocao Could you please have a look at this issue?

**Comment by matteocao** [comment]
I think there is a compatibility issue between the new version of torch and captum. 

I will try to see if I can update torch: however, this may be a complex PR.

**Comment by raphaelreinauer** [comment]
We are testing the notebook `giotto-deep/examples/basic_tutorial_image.ipynb` in our CI/CD pipeline
https://github.com/giotto-ai/giotto-deep/blob/1bf3103743835a75b5c0f3f9d0de948b0b071f85/.github/workflows/python-package.yml#L62
Hence verifying that notebook runs with the specific version `torch==1.12.1`. 
The -U flag in the pip install command tells pip to upgrade all specified packages to the newest available version, including dependencies. So even if requirements.txt specified torch==1.12.1, the -U would override that.
@WurmD  To install the compatible torch version please run
```
pip install torch==1.12.1
```
this should fix the error you are seeing.
