### ISSUE TITLE
New method `get_activation_gradient`

### ISSUE THREAD

**Issue by matteocao** [giotto-ai/giotto-deep#71]
**Is your feature request related to a problem? Please describe.**

There is a need to build a method that extracts the gradients with respect to the activations, hence:

```latex
\frac{d(Loss)}{d (activation_i)}
```

**Describe the solution you'd like**

A possible solution would be to `deepcopy` the model, add biases, compute the gradient with respect to biases.
**Describe alternatives you've considered**

Not sure, open to suggestions.
**Additional context**

**Comment by raphaelreinauer** [comment]
Is this still relevant?

**Comment by nberkouk** [comment]
I tried to make it work and it did not. Then Matteo tried and it seemed a bit tricky. It is relevant at least to my own personal research on adversarial attacks, but maybe it does not need to be part of the library, or it can be developed later

**Comment by RaphaelLilt** [comment]
@matteocao Can we close this issue?
