### ISSUE TITLE
Add GPUs to pods

### ISSUE THREAD

**Issue by matteocao** [giotto-ai/giotto-deep#96]
**Is your feature request related to a problem? Please describe.**

When distributing computations over K8, only CPU are used.
**Describe the solution you'd like**

We shall probably add a NodeSelector description in the yaml files and test if the current workers dockers support GPUs: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#ubuntu

**Describe alternatives you've considered**

None
**Additional context**

**Comment by raphaelreinauer** [comment]
Are you still working on that issue @sydneyhauke?

**Comment by RaphaelLilt** [comment]
@matteocao Can we close this issue?
